// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package encryption.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import encryption.pgp.PGPFileProcessor;
import encryption.proxies.microflows.Microflows;

/**
 * Encrypt the FileDocument using PGP encryption.
 * This is allowed to be the same FileDocument instance and the action will just store the decrypted file in the entity.
 * 
 * The certificate must be a File containing a valid PGP key ring (matching the document) and the certificate must have a passphrase entered in the attribute
 * 
 * This action will either return true or an exception
 */
public class PGPDecryptDocument extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use PrivateDecryptionKey.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __PrivateDecryptionKey;
	private final encryption.proxies.PGPCertificate PrivateDecryptionKey;
	/** @deprecated use DocumentToDecrypt.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DocumentToDecrypt;
	private final system.proxies.FileDocument DocumentToDecrypt;
	/** @deprecated use OutputDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OutputDocument;
	private final system.proxies.FileDocument OutputDocument;

	public PGPDecryptDocument(
		IContext context,
		IMendixObject _privateDecryptionKey,
		IMendixObject _documentToDecrypt,
		IMendixObject _outputDocument
	)
	{
		super(context);
		this.__PrivateDecryptionKey = _privateDecryptionKey;
		this.PrivateDecryptionKey = _privateDecryptionKey == null ? null : encryption.proxies.PGPCertificate.initialize(getContext(), _privateDecryptionKey);
		this.__DocumentToDecrypt = _documentToDecrypt;
		this.DocumentToDecrypt = _documentToDecrypt == null ? null : system.proxies.FileDocument.initialize(getContext(), _documentToDecrypt);
		this.__OutputDocument = _outputDocument;
		this.OutputDocument = _outputDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _outputDocument);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		PGPFileProcessor p = new PGPFileProcessor();
		p.setInputFileDocument(this.DocumentToDecrypt.getMendixObject());
		p.setOutputFileDocument(this.OutputDocument.getMendixObject());
		String decryptedPassPhrase = Microflows.decrypt(getContext(), this.PrivateDecryptionKey.getPassPhrase_Encrypted());
		p.setPassphrase(decryptedPassPhrase);
		p.setSecretKeyFileName(this.PrivateDecryptionKey.getMendixObject());

		return p.decrypt(getContext());

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PGPDecryptDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
