// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package encryption.actions;

import org.bouncycastle.openpgp.PGPSecretKeyRingCollection;
import org.bouncycastle.openpgp.PGPUtil;
import org.bouncycastle.openpgp.operator.bc.BcKeyFingerprintCalculator;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class ValidatePrivateKeyRing extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use PrivateKeyRing.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __PrivateKeyRing;
	private final encryption.proxies.PGPCertificate PrivateKeyRing;

	public ValidatePrivateKeyRing(
		IContext context,
		IMendixObject _privateKeyRing
	)
	{
		super(context);
		this.__PrivateKeyRing = _privateKeyRing;
		this.PrivateKeyRing = _privateKeyRing == null ? null : encryption.proxies.PGPCertificate.initialize(getContext(), _privateKeyRing);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		//This function will throw an exception if the inputstream isn't a valid private keyring
		new PGPSecretKeyRingCollection(PGPUtil.getDecoderStream(Core.getFileDocumentContent(getContext(), this.PrivateKeyRing.getMendixObject()) ), new BcKeyFingerprintCalculator());
		
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ValidatePrivateKeyRing";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
