// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.auth0.jwt.JWT;
import com.auth0.jwt.interfaces.DecodedJWT;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * Decodes a JWT string into a plain text JSON for the header and payload. This enables the user to implement a specific JSON mapping that decodes the header or payload. Throws an exception when the token could not be decoded or verified.
 */
public class DecodeJWT extends CustomJavaAction<IMendixObject>
{
	private final java.lang.String encodedJWT;

	public DecodeJWT(
		IContext context,
		java.lang.String _encodedJWT
	)
	{
		super(context);
		this.encodedJWT = _encodedJWT;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		DecodedJWT jwt = JWT.decode(encodedJWT);
		oidc.proxies.JWT mxJWT = new oidc.proxies.JWT(getContext());
		mxJWT.setexp(jwt.getExpiresAt());
		mxJWT.setiat(jwt.getIssuedAt());
		mxJWT.setiss(jwt.getIssuer());
		mxJWT.setjti(jwt.getId());
		mxJWT.setkid(jwt.getKeyId());
		mxJWT.setnbf(jwt.getNotBefore());
		mxJWT.setsub(jwt.getSubject());
		return mxJWT.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DecodeJWT";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
