// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.databind.ObjectMapper;

public class GetIssuerFromToken extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String DecodedAccesstoken;

	public GetIssuerFromToken(
		IContext context,
		java.lang.String _decodedAccesstoken
	)
	{
		super(context);
		this.DecodedAccesstoken = _decodedAccesstoken;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		HashMap<String, String> readValue = new ObjectMapper().readValue(DecodedAccesstoken, HashMap.class);
		return readValue.get("iss");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetIssuerFromToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
