// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import java.util.HashMap;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetScopeFromToken extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String DecodedJWT;

	public GetScopeFromToken(
		IContext context,
		java.lang.String _decodedJWT
	)
	{
		super(context);
		this.DecodedJWT = _decodedJWT;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		HashMap<String, String> readValue = new ObjectMapper().readValue(DecodedJWT, HashMap.class);
		return readValue.get("scope");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetScopeFromToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
