// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<MxObject>}
 */
export async function JSA_Object_CreateAction() {
	// BEGIN USER CODE

	return new Promise((resolve, reject) => {
		mx.data.create({
			entity: "Java_JavascriptModule.MxObject",
			callback: (mxobj) => {
				mxobj.set("Name","mx001");
				resolve(mxobj);
			},
			error: (e) => {
				reject("Could not create object:", e.message);
			}
		});
	});

	// END USER CODE
}
