// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JSA_SideBarRemoveClass() {
	// BEGIN USER CODE
	
	let selectElement = document.querySelectorAll('.mx-navigationtree-collapsed');
	
	//null check
	if(typeof selectElement == "undefined" || selectElement == null || selectElement == ""){}
	else{
		let elementLength = selectElement.length;

		for(var i = 0; i < elementLength; i++){
			selectElement[i].classList.remove('mx-navigationtree-collapsed');
		}
	}

	// END USER CODE
}
