// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package loginssomodule.actions;

import java.io.IOException;
import javax.servlet.http.HttpServletResponse;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.IUser;
import com.mendix.webui.CustomJavaAction;

public class JAT_MendixSSOLogin extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String UserId;

	public JAT_MendixSSOLogin(
		IContext context,
		java.lang.String _userId
	)
	{
		super(context);
		this.UserId = _userId;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		_Logger.info("Get User ID : " + UserId);
		
		try {
			IContext ict = this.getContext();
			
			IUser user = Core.getUser(ict, UserId);
			
			if(user != null) {
				ISession session = Core.initializeSession(user, null);
				
				if(ict.getRuntimeResponse().isPresent()) {
					//Get RuntimeResponse
					IMxRuntimeResponse res = ict.getRuntimeResponse().get();
					
					//Client 쿠키에 session 정보 및 xsid 삽입
					setCookies(res, session);
					
					//쿠키에 담긴 정보를 가지고 페이지 이동
					sendRedirect(res, "/");
					
					return true;
				}
			}
		}catch (Exception e) {
			// TODO: handle exception
			_Logger.error(e.getMessage());
			_Logger.error(e.getStackTrace());
		}
		
		return false;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAT_MendixSSOLogin";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode _Logger = Core.getLogger("Mendix SSO Login");
	
	protected void setCookies(IMxRuntimeResponse res, ISession session) {
		//addCookie
		res.addCookie("XASSESSIONID", session.getId().toString(), "/", "", -1, true);
		res.addCookie("XASID", "0." + Core.getXASId(), "/", "", -1, true);
	}
	
	protected void sendRedirect(IMxRuntimeResponse res, String redirectURL) throws IOException {
		//get HttpServletResponse
		HttpServletResponse response = res.getHttpServletResponse();
		
		response.sendRedirect(redirectURL);
	}
	// END EXTRA CODE
}
