// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oql.actions;

import java.util.List;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import oql.implementation.OQL;

/**
 * This action executes the OQL statement and returns the amount of rows which will be returned by the OQL statement.
 * The main purpose of this action was to avoid overhead of object creation while the interest is to determine if a record within the database exists.
 */
public class CountRowsOQLStatement extends CustomJavaAction<java.lang.Long>
{
	private final java.lang.String statement;
	private final java.lang.Long amount;
	private final java.lang.Long offset;

	public CountRowsOQLStatement(
		IContext context,
		java.lang.String _statement,
		java.lang.Long _amount,
		java.lang.Long _offset
	)
	{
		super(context);
		this.statement = _statement;
		this.amount = _amount;
		this.offset = _offset;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext().createSudoClone();
		ILogNode logger = Core.getLogger(this.getClass().getSimpleName());
		
		logger.debug("Mapping parameters.");
		Map<String, Object> parameters = OQL.getNextParameters();
		Long result = 
				OQL.countRowsOQL(context, statement, amount, parameters);	
		
		OQL.resetParameters();
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CountRowsOQLStatement";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
