// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oql.actions;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.Date;
import java.util.Map.Entry;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataColumnSchema;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataRow;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataTable;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataTableSchema;
import com.mendix.systemwideinterfaces.connectionbus.requests.IParameterMap;
import com.mendix.systemwideinterfaces.connectionbus.requests.IRetrievalSchema;
import com.mendix.systemwideinterfaces.connectionbus.requests.types.IOQLTextGetRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.opencsv.CSVWriter;
import oql.implementation.OQL;
import system.proxies.FileDocument;

public class ExportOQLToCSV extends CustomJavaAction<IMendixObject>
{
	private final java.lang.String statement;
	private final java.lang.String returnEntity;
	private final java.lang.Boolean removeNewLinesFromValues;
	private final java.lang.Boolean zipResult;
	private final java.lang.Boolean exportHeaders;
	private final java.lang.String separatorChar;
	private final java.lang.String quoteChar;
	private final java.lang.String escapeChar;

	public ExportOQLToCSV(
		IContext context,
		java.lang.String _statement,
		java.lang.String _returnEntity,
		java.lang.Boolean _removeNewLinesFromValues,
		java.lang.Boolean _zipResult,
		java.lang.Boolean _exportHeaders,
		java.lang.String _separatorChar,
		java.lang.String _quoteChar,
		java.lang.String _escapeChar
	)
	{
		super(context);
		this.statement = _statement;
		this.returnEntity = _returnEntity;
		this.removeNewLinesFromValues = _removeNewLinesFromValues;
		this.zipResult = _zipResult;
		this.exportHeaders = _exportHeaders;
		this.separatorChar = _separatorChar;
		this.quoteChar = _quoteChar;
		this.escapeChar = _escapeChar;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		final int PAGE_SIZE = 10000;
		
		ILogNode logger = Core.getLogger(this.getClass().getSimpleName());
		String suffix = ".csv";
		if (this.zipResult) {
			suffix += ".zip";
		}
		File tmpFile = File.createTempFile("Export", suffix);
		OutputStream os;
		FileOutputStream fos = new FileOutputStream(tmpFile);
		ZipOutputStream zos = null;
		if (zipResult) {
			zos = new ZipOutputStream(fos);
			zos.putNextEntry(new ZipEntry(tmpFile.getName().replaceAll(".zip", "")));
			os = zos;
		} else {
			os = fos;
		}
		
        CSVWriter writer = new CSVWriter(new OutputStreamWriter(os), 
                this.separatorChar.charAt(0), 
                this.quoteChar != null ? this.quoteChar.charAt(0) : CSVWriter.NO_QUOTE_CHARACTER,
                this.escapeChar != null ? this.escapeChar.charAt(0) : CSVWriter.NO_ESCAPE_CHARACTER, 
                "\r\n");

		IMendixObject result = Core.instantiate(getContext(), this.returnEntity);
		
		logger.debug("Executing query");
		
		int offset = 0;
		while(true) {
			logger.debug("Executing query offset " + offset);
			
			
			IContext context = getContext().createSudoClone();
			IDataTable results = Core.retrieveOQLDataTable(context, buildRequest(statement, offset, PAGE_SIZE));

			IDataTableSchema tableSchema = results.getSchema();
			
			if (this.exportHeaders && offset == 0) {
				String[] headers = new String[tableSchema.getColumnCount()];
				int index = 0;
				for (IDataColumnSchema columnSchema : tableSchema.getColumnSchemas()) {
					headers[index] = columnSchema.getName();
					index++;
				}
				writer.writeNext(headers);
			}
			
			for (IDataRow row : results.getRows()) {
				String[] values = new String[tableSchema.getColumnCount()];
				for (int i = 0; i < tableSchema.getColumnCount(); i++) {
					Object value = row.getValue(getContext(), i);
					if (value == null) {
						values[i] = "";
					} else {
						if (value instanceof Date) {
							values[i] = Long.toString(((Date) value).getTime()); // use timestamp to export for more precision than just seconds.
						} else if (value instanceof IMendixIdentifier) {
							values[i] = Long.toString(((IMendixIdentifier) value).toLong());
						} else {
							values[i] = value.toString();
						}
						if (this.removeNewLinesFromValues) {
							values[i] = values[i].replaceAll("\r", " ").replaceAll("\n", "");
						}
					}
				}
				writer.writeNext(values);
			}
			
			if (results.getRowCount() != PAGE_SIZE) {
				break;
			}
			results.getRows().clear();
			offset += PAGE_SIZE;
		}
		writer.close();
		result.setValue(getContext(), FileDocument.MemberNames.Name.toString(), tmpFile.getName());
		Core.storeFileDocumentContent(getContext(), result, new FileInputStream(tmpFile));
		tmpFile.delete();
		OQL.resetParameters();
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExportOQLToCSV";
	}

	// BEGIN EXTRA CODE
	private IOQLTextGetRequest buildRequest(String statement, int offset, int pagesize) {
		IOQLTextGetRequest request;
		try {
			request = Core.createOQLTextGetRequestFromDataSet(statement); 
		} catch (IllegalArgumentException e) {
			request = Core.createOQLTextGetRequest();
			request.setQuery(statement);
		}
		
		IParameterMap parameterMap = request.createParameterMap();
		IRetrievalSchema schema = Core.createRetrievalSchema();
		schema.setAmount(pagesize);
		schema.setOffset(offset);
		request.setRetrievalSchema(schema);
		for (Entry<String, Object> entry : OQL.getNextParameters().entrySet()) {
			parameterMap.put(entry.getKey(), entry.getValue());
		}
		request.setParameters(parameterMap);
		return request;
	}
	// END EXTRA CODE
}
