// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package excelimporter.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import excelimporter.reader.ExcelImporter;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Synchronise all excel columns and add/update/remove the existing columns from the template in the parameter.
 * The return value is irrelevant and will be always true
 */
public class GetHeaderInformationFromExcelFile extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use TemplateObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TemplateObject;
	private final excelimporter.proxies.Template TemplateObject;
	/** @deprecated use ExcelFileDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ExcelFileDocument;
	private final excelimporter.proxies.TemplateDocument ExcelFileDocument;

	public GetHeaderInformationFromExcelFile(
		IContext context,
		IMendixObject _templateObject,
		IMendixObject _excelFileDocument
	)
	{
		super(context);
		this.__TemplateObject = _templateObject;
		this.TemplateObject = _templateObject == null ? null : excelimporter.proxies.Template.initialize(getContext(), _templateObject);
		this.__ExcelFileDocument = _excelFileDocument;
		this.ExcelFileDocument = _excelFileDocument == null ? null : excelimporter.proxies.TemplateDocument.initialize(getContext(), _excelFileDocument);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ExcelImporter.getColumns(this.getContext(), this.TemplateObject.getMendixObject(), this.ExcelFileDocument.getMendixObject() );
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetHeaderInformationFromExcelFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
