// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_javascriptmodule.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JAT_RetriveQuerySelectorList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private final java.lang.String Name;
	private final java.lang.Long Age;

	public JAT_RetriveQuerySelectorList(
		IContext context,
		java.lang.String _name,
		java.lang.Long _age
	)
	{
		super(context);
		this.Name = _name;
		this.Age = _age;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> results = Core.createXPathQuery("//Java_JavascriptModule.Student[Name=$value1 and Age=$value2]")
				.setVariable("value1", Name)
				.setVariable("value2", Age)
				.setDepth(1)
				.execute(getContext());
		
		return results;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAT_RetriveQuerySelectorList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
