// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_javascriptmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import communitycommons.ORM;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JAT_Object_GetGUID extends CustomJavaAction<java.lang.Long>
{
	/** @deprecated use MxObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MxObject;
	private final java_javascriptmodule.proxies.MxObject MxObject;

	public JAT_Object_GetGUID(
		IContext context,
		IMendixObject _mxObject
	)
	{
		super(context);
		this.__MxObject = _mxObject;
		this.MxObject = _mxObject == null ? null : java_javascriptmodule.proxies.MxObject.initialize(getContext(), _mxObject);
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		//Case1
		//__MxObject.getId().toLong()
		
		//Case2
		//MxObject.getMendixObject().getId().toLong();
		
		//Case3
		long objectguid = ORM.getGUID(MxObject.getMendixObject());
		
		return objectguid;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAT_Object_GetGUID";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
