// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_javascriptmodule.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JAT_RetriveQuerySelector extends CustomJavaAction<IMendixObject>
{
	private final java.lang.String Name;

	public JAT_RetriveQuerySelector(
		IContext context,
		java.lang.String _name
	)
	{
		super(context);
		this.Name = _name;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> results = Core.createXPathQuery("//Java_JavascriptModule.Student[Name=$value]")
				.setVariable("value", Name)
				.setDepth(1)
				.execute(getContext());
		
		return results.get(0);
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAT_RetriveQuerySelector";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
