// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_javascriptmodule.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JAT_Logging extends CustomJavaAction<java.lang.Void>
{
	public JAT_Logging(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		_Logger.trace("trace Log Test");
		_Logger.debug("debug Log Test");
		_Logger.info("info Log Test");
		_Logger.warn("warning Log Test");
		_Logger.error("error Log Test");
		_Logger.critical("critical Log Test");
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAT_Logging";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode _Logger = Core.getLogger("Logging");
	// END EXTRA CODE
}
