// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_javascriptmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java_javascriptmodule.proxies.MxObject;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JAT_Object_CreateAction extends CustomJavaAction<IMendixObject>
{
	public JAT_Object_CreateAction(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MxObject mxobject = new MxObject(this.getContext());
		
		mxobject.setName("mx001");
		
		return mxobject.getMendixObject();
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAT_Object_CreateAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
